apiVersion: v2
name: volume-syncing-controller
description: "Controller that injects rclone into Pods that are going to be created. Allows to synchronize service periodically, and restore on Pod creation"
type: application
version: 0.1.0
appVersion: "main"  # replaced by CI on build stage
