---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "volume-syncing-operator.fullname" . }}
rules:
    # parsing incoming requests
    - apiGroups:
          - ""
      resources:
          - pods
          - namespaces
      verbs:
          - get
          - list

    # injecting secrets into target namespace
    - apiGroups:
          - ""
      resources:
          - secrets
      verbs:
          - get
          - list
          - create
          - update
          - delete

    - apiGroups:
          - "riotkit.org"
      resources:
          - podfilesystemsyncs
      verbs:
          - get
          - list

    - apiGroups:
          - "riotkit.org"
      resources:
          - podfilesystemsyncs/status
      verbs:
          - get
          - list
          - create
          - update
          - delete

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: {{ include "volume-syncing-operator.fullname" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "volume-syncing-operator.fullname" . }}
subjects:
    - kind: ServiceAccount
      name: {{ include "volume-syncing-operator.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
