{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Values.serviceAccount.name }}
    labels:
        {{- include "volume-syncing-controller.labels" . | nindent 8 }}
  {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
